USE bgfc_inventory;
INSERT IGNORE INTO roles(role_name,description) VALUES ('ADMINISTRATOR','Full system access'),('INVENTORY_OFFICER','Inventory operations and reports'),('STAFF','Inventory viewing, stock out, and own transaction history');
INSERT IGNORE INTO categories(category_code,category_name,description) VALUES ('CAT-001','Office Supplies','Supplies used by school offices'),('CAT-002','IT Equipment','Computers and peripherals'),('CAT-003','Furniture','School and office furniture'),('CAT-004','Cleaning Supplies','Cleaning and sanitation materials'),('CAT-005','Laboratory Equipment','Laboratory assets and equipment'),('CAT-006','Printer Supplies','Printer consumables');
INSERT IGNORE INTO suppliers(supplier_code,supplier_name,contact_person,contact_number,email,address) VALUES ('SUP-001','ABC Office Supplies','Ana Cruz','09171234567','sales@abcoffice.example','Manila'),('SUP-002','IT Solutions PH','Mark Reyes','09181234567','orders@itsolutions.example','Quezon City');
INSERT IGNORE INTO departments(department_code,department_name,description) VALUES ('DEP-001','Administration','School administration'),('DEP-002','Registrar','Registrar office'),('DEP-003','Accounting','Accounting office'),('DEP-004','Library','School library'),('DEP-005','BSIT Laboratory','BSIT computer laboratory'),('DEP-006','Guidance','Guidance office');
-- Exam-only account: admin / password. Change after the first login outside a demonstration environment.
INSERT INTO users(full_name,username,email,password,role,status) VALUES ('System Administrator','admin','admin@bgfc.local','$2b$12$4AoqEYYZ0fx1NRjrgkDv7OJctnhFp/pCUgzf8i/HYiLwdsbpK2ItK','ADMINISTRATOR','ACTIVE') ON DUPLICATE KEY UPDATE password=VALUES(password),role='ADMINISTRATOR',status='ACTIVE';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0001','Bond Paper A4',id,'A4 copy paper','Ream',50,10 FROM categories WHERE category_code='CAT-001';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0002','Ballpen Black',id,'Black ballpoint pen','Piece',150,30 FROM categories WHERE category_code='CAT-001';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0003','Ink Epson 003',id,'Original Epson ink','Bottle',5,10 FROM categories WHERE category_code='CAT-006';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0004','Folder Brown',id,'Document folder','Piece',8,10 FROM categories WHERE category_code='CAT-001';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0005','Printer Paper',id,'Printer paper','Ream',40,10 FROM categories WHERE category_code='CAT-006';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0006','Keyboard',id,'USB keyboard','Piece',12,5 FROM categories WHERE category_code='CAT-002';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0007','Mouse',id,'USB mouse','Piece',15,5 FROM categories WHERE category_code='CAT-002';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0008','HDMI Cable',id,'HDMI display cable','Piece',10,4 FROM categories WHERE category_code='CAT-002';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0009','Extension Cord',id,'Electrical extension cord','Piece',7,3 FROM categories WHERE category_code='CAT-002';
INSERT IGNORE INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) SELECT 'ITM-0010','Office Chair',id,'Ergonomic office chair','Piece',10,3 FROM categories WHERE category_code='CAT-003';
