const db = require('../database/db');
const audit = require('../middleware/auditLogger');
const statusSql = "CASE WHEN i.quantity=0 THEN 'Out of Stock' WHEN i.quantity<=i.reorder_level THEN 'Low Stock' ELSE 'In Stock' END";
exports.index = async (req,res,next)=>{ try { const {search='',category='',status=''}=req.query; let sql=`SELECT i.*,c.category_name,${statusSql} stock_status FROM items i LEFT JOIN categories c ON c.id=i.category_id WHERE i.is_active=1`; const p=[]; if(search){sql+=' AND (i.item_code LIKE ? OR i.item_name LIKE ? OR i.description LIKE ?)';p.push(`%${search}%`,`%${search}%`,`%${search}%`)} if(category){sql+=' AND i.category_id=?';p.push(category)} if(status){sql+=` AND ${statusSql}=?`;p.push(status)} sql+=' ORDER BY i.created_at DESC'; const [[items],[categories]]=await Promise.all([db.execute(sql,p),db.query('SELECT * FROM categories WHERE is_active=1 ORDER BY category_name')]); res.render('items/index',{title:'Items',items,categories,filters:{search,category,status}});}catch(e){next(e)} };
exports.form = async(req,res,next)=>{try{const [categories]=await db.query('SELECT * FROM categories WHERE is_active=1 ORDER BY category_name'); let item=null;if(req.params.id){const [r]=await db.execute('SELECT * FROM items WHERE id=? AND is_active=1',[req.params.id]);item=r[0];if(!item)return res.status(404).render('errors/error',{title:'Not found',status:404,message:'Item not found.'})}res.render('items/form',{title:item?'Edit Item':'Create Item',item,categories});}catch(e){next(e)}};
exports.view=async(req,res,next)=>{try{const [r]=await db.execute(`SELECT i.*,c.category_name,${statusSql} stock_status FROM items i LEFT JOIN categories c ON c.id=i.category_id WHERE i.id=? AND i.is_active=1`,[req.params.id]);if(!r[0])return res.status(404).render('errors/error',{title:'Not found',status:404,message:'Item not found.'});const [tx]=await db.execute('SELECT t.*,u.full_name FROM inventory_transactions t LEFT JOIN users u ON u.id=t.user_id WHERE item_id=? ORDER BY transaction_date DESC LIMIT 20',[req.params.id]);res.render('items/view',{title:r[0].item_name,item:r[0],transactions:tx});}catch(e){next(e)}};
exports.create=async(req,res,next)=>{try{const {item_code,item_name,category_id,description,unit,quantity,reorder_level}=req.body;if(!item_code||!item_name||!unit||!category_id||!Number.isInteger(Number(quantity))||Number(quantity)<0||Number(reorder_level)<0){req.flash('error','Please provide valid values for all required fields.');return res.redirect('/items/create')}const [r]=await db.execute('INSERT INTO items(item_code,item_name,category_id,description,unit,quantity,reorder_level) VALUES(?,?,?,?,?,?,?)',[item_code,item_name,category_id,description||null,unit,Number(quantity),Number(reorder_level)]);await audit(req,'ADDED_ITEM','Items',`Created ${item_code} - ${item_name}`);req.flash('success','Item successfully created.');res.redirect(`/items/${r.insertId}`)}catch(e){if(e.code==='ER_DUP_ENTRY'){req.flash('error','Item code already exists.');return res.redirect('/items/create')}next(e)}};
exports.update=async(req,res,next)=>{try{const {item_name,category_id,description,unit,reorder_level}=req.body;if(!item_name||!category_id||!unit||Number(reorder_level)<0){req.flash('error','Please provide valid required values.');return res.redirect(`/items/${req.params.id}/edit`)}await db.execute('UPDATE items SET item_name=?,category_id=?,description=?,unit=?,reorder_level=? WHERE id=? AND is_active=1',[item_name,category_id,description||null,unit,Number(reorder_level),req.params.id]);await audit(req,'UPDATED_ITEM','Items',`Updated item #${req.params.id}`);req.flash('success','Item successfully updated.');res.redirect('/items')}catch(e){next(e)}};
exports.delete=async(req,res,next)=>{const conn=await db.getConnection();try{await conn.beginTransaction();const [items]=await conn.execute('SELECT item_code,item_name FROM items WHERE id=? FOR UPDATE',[req.params.id]);if(!items[0]){await conn.rollback();req.flash('error','Item not found.');return res.redirect('/items')}const [[usage]]=await conn.execute('SELECT COUNT(*) transaction_count FROM inventory_transactions WHERE item_id=?',[req.params.id]);if(Number(usage.transaction_count)>0){await conn.rollback();req.flash('error','This item cannot be deleted because it has transaction history.');return res.redirect('/items')}await conn.execute('DELETE FROM items WHERE id=?',[req.params.id]);await conn.commit();await audit(req,'DELETED_ITEM','Items',`Deleted ${items[0].item_code} - ${items[0].item_name}`);req.flash('success','Item successfully deleted.');res.redirect('/items')}catch(e){await conn.rollback();next(e)}finally{conn.release()}};
